apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"heartbeat","namespace":"workerservice"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"heartbeat"}},"template":{"metadata":{"labels":{"app":"heartbeat"}},"spec":{"containers":[{"image":"cloudnativedotnetregistrylg1996.azurecr.io.azurecr.io/heartbeatapi:latest","name":"heartbeat","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2021-10-05T06:45:42Z"
  generation: 1
  name: heartbeat
  namespace: workerservice
  resourceVersion: "16268"
  uid: ca988ffb-e8a9-4aae-ab7d-46dd8f658acc
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: heartbeat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: heartbeat
    spec:
      containers:
      - image: cloudnativedotnetregistrylg1996.azurecr.io.azurecr.io/heartbeatapi:latest
        imagePullPolicy: Always
        name: heartbeat
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-10-05T06:45:42Z"
    lastUpdateTime: "2021-10-05T06:45:42Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-10-05T06:45:42Z"
    lastUpdateTime: "2021-10-05T06:45:42Z"
    message: ReplicaSet "heartbeat-b4955dfbd" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 10
  unavailableReplicas: 10
  updatedReplicas: 10
